# Docker Compose versión 3.8

services:
  # Aplicación Node.js (Backend)
  backend:
    build:
      context: .
      dockerfile: dockerfile
    container_name: routerapp_backend
    restart: unless-stopped
    ports:
      - "3005:3005"
    env_file:
      - .env
    environment:
      - JWT_SECRET=tu-jwt-secret-super-seguro-para-produccion
      - JWT_EXPIRES_IN=24h
    networks:
      - routerapp_network
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3005/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Mongo Express (opcional)
  mongo-express:
    image: mongo-express:1.0.0
    container_name: routerapp_mongo_express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: darwinadministradortotaldeladb
      ME_CONFIG_MONGODB_ADMINPASSWORD: contramaseguradelmundomundialisimo
      ME_CONFIG_MONGODB_URL: mongodb://darwinadministradortotaldeladb:contramaseguradelmundomundialisimo@18.191.163.61:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    networks:
      - routerapp_network

networks:
  routerapp_network:
    driver: bridge
